// const projectImages = [
//   "/mebelivam-img/проекти/IMG_9338.JPG",
//   "/mebelivam-img/проекти/IMG_9339.JPG",
//   "/mebelivam-img/проекти/IMG_9340.JPG",
//   "/mebelivam-img/проекти/IMG_9341.JPG",
//   "/mebelivam-img/проекти/IMG_9342.JPG",
//   "/mebelivam-img/проекти/IMG_9343.JPG",
//   "/mebelivam-img/проекти/IMG_9344.JPG",
//   "/mebelivam-img/проекти/IMG_9345.JPG",
//   "/mebelivam-img/проекти/IMG_9346.JPG",
//   "/mebelivam-img/проекти/IMG_9347.JPG",
//   "/mebelivam-img/проекти/IMG_9348.JPG",
//   "/mebelivam-img/проекти/IMG_9349.JPG",
//   "/mebelivam-img/проекти/IMG_9350.JPG",
//   "/mebelivam-img/проекти/IMG_9351.JPG",
//   "/mebelivam-img/проекти/IMG_9352.JPG",
//   "/mebelivam-img/проекти/IMG_9353.JPG",
//   "/mebelivam-img/проекти/IMG_9354.JPG",
//   "/mebelivam-img/проекти/IMG_9355.JPG",
//   "/mebelivam-img/проекти/IMG_9356.JPG",
//   "/mebelivam-img/проекти/IMG_9357.JPG",
//   "/mebelivam-img/проекти/IMG_9358.JPG",
//   "/mebelivam-img/проекти/IMG_9359.JPG",
//   "/mebelivam-img/проекти/IMG_9360.JPG",
//   "/mebelivam-img/проекти/3-kitchen-program.JPG",
//   "/mebelivam-img/проекти/IMG_9362.JPG",
//   "/mebelivam-img/проекти/1-our-kitchen-program.JPG",
//   "/mebelivam-img/проекти/2-kitchen-program.JPG",
//   "/mebelivam-img/проекти/IMG_9365.JPG",
//   "/mebelivam-img/проекти/IMG_9366.JPG",
//   "/mebelivam-img/проекти/IMG_9367.JPG",
// ];
//
// export default projectImages;