const realImages = [
  "/mebelivam-img/реални-завършени/IMG_9368.JPG",
  "/mebelivam-img/реални-завършени/IMG_9369.JPG",
  "/mebelivam-img/реални-завършени/IMG_9371.JPG",
  "/mebelivam-img/реални-завършени/IMG_9373.JPG",
  "/mebelivam-img/реални-завършени/IMG_9375.JPG",
  "/mebelivam-img/реални-завършени/IMG_9382.JPG",
  "/mebelivam-img/реални-завършени/IMG_9385.JPG",
  "/mebelivam-img/реални-завършени/IMG_9386.JPG",
  "/mebelivam-img/реални-завършени/IMG_9389.JPG",
  "/mebelivam-img/реални-завършени/IMG_9391.JPG",
  "/mebelivam-img/реални-завършени/IMG_9392.JPG",
  "/mebelivam-img/реални-завършени/img-2.jpg",
  "/mebelivam-img/реални-завършени/img-3.jpg",
  "/mebelivam-img/реални-завършени/img-4.jpg",
  "/mebelivam-img/реални-завършени/img-5.jpg",
  "/mebelivam-img/реални-завършени/img-6.jpg",
  "/mebelivam-img/реални-завършени/img-7.jpg",
  "/mebelivam-img/реални-завършени/img-8.jpg",
  "/mebelivam-img/реални-завършени/img-9.jpg",
  "/mebelivam-img/реални-завършени/img-10.jpg",
  "/mebelivam-img/реални-завършени/img-12.jpg",
  "/mebelivam-img/реални-завършени/img-15.jpg",
  "/mebelivam-img/реални-завършени/img-16.jpg",
  "/mebelivam-img/реални-завършени/img-17.jpg",
  "/mebelivam-img/реални-завършени/img-20.jpg",
  "/mebelivam-img/реални-завършени/img-21.jpg",
  "/mebelivam-img/реални-завършени/img-22.jpg",
  "/mebelivam-img/реални-завършени/img-23.jpg",
  "/mebelivam-img/реални-завършени/img-25.jpg",
  "/mebelivam-img/реални-завършени/img-26.jpg",
  "/mebelivam-img/реални-завършени/img-28.jpg",
  "/mebelivam-img/реални-завършени/img-33.jpg",
];

export default realImages; 